# -*- coding: utf-8 -*-
"""Sesión 11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166YvrB7-LW9luk4YJn_jpRftwoIM-tU3
"""

d1={
    "Nombre": "Carolina",
    "Edad": 26,
    "Documento": 1004671669
}
print(d1)

d2 = dict([
    ("Nombre", "Carolina"),
    ("Edad", 26),
    ("Documento", 1004671669)
])
print(d2)

d3 = dict(Nombre = "Carolina",
          Edad = 26,
          Documento = 1004671669)
print(d3)

print(d1["Nombre"])
print(d1.get("Nombre"))
print(d1["Edad"])
print(d1.get("Edad"))
print(d1["Documento"])
print(d1.get("Documento"))

d1["Nombre"] = "Laura"
print(d1)

d1["Direccion"] = "Calle 123"
print(d1)

for x in d1:
    print(x)

for x in d1:
    print(d1[x])

for x, y in d1.items():
    print(x, y)

anidado1 ={"a": 1, "b": 2}
anidado2 ={"a": 1, "b": 2}

d = {
    "anidado1" : anidado1,
    "anidado2" : anidado2
}

print(d)

d = {"a":1, "b":2}

d.clear()

print(d)

d = {"a": 1, "b": 2}
print(d.get("a"))
print(d.get("c"))

d = {"a": 1,"b": 2}
it = d.items()
print(it)
print(list(it))
print(list(it)[0][0])

d = {"a": 1, "b": 2}
print(d.keys())
print(list(d.keys()))

d = {"a": 1, "b": 2}
print(list(d.values()))

d = {"a": 1, "b": 2}
d.pop("a")
print(d)

d = {"a": 1, "b": 2}
d.pop("c", 1)
print(d)

d = {"a":1, "b":2}
d.popitem()
print(d)

d1 = {"a":1, "b":2}
d2 = {"c":0, "d":400}
d1.update(d2)
print(d1)