# -*- coding: utf-8 -*-
"""Sesion12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154bDk3-Fq2EoM7LJTa_hmztsnthZLCeP
"""

# Creación de una tupla con diferentes tipos de datos
mi_tupla = (1,2,3,"hola", True)
print(mi_tupla)  # Imprime la tupla completa

# Tupla con elementos repetidos
t = (1,1,2,3,3,3)
print(t)

# Las listas son mutables, se pueden modificar
lista = [1,2,3]
lista[0] = 10   # Cambia el primer elemento de 1 a 10
print(lista)

# Las tuplas son inmutables, no se pueden modificar
tupla=(1,2,3)
tupla[0] = 10   # ❌ ERROR: No se puede reasignar un valor en una tupla
print(tupla)

# Otro ejemplo con tuplas inmutables
cordenadas = (20.7128, -74.0060)
cordenadas[0] = 41.1  # ❌ ERROR: No se puede cambiar un valor en una tupla

# Diferentes formas de crear tuplas
tupla = (1,2,3)
tupla2 = ("a","b","c")
tupla3 = (1,"hola", 3, 5)
tupla4 = ()       # Tupla vacía
tupla5 = (5,)     # Tupla con un solo elemento (necesita la coma)

print(tupla)
print(tupla2)
print(tupla3)
print(tupla4)
print(tupla5)

# Acceso a elementos de una tupla
tupla = ("python", 2025, True)
print(tupla[0])   # python
print(tupla[1])   # 2025
print(tupla[-1])  # True (último elemento)

# Slicing en tuplas
tupla = (10,20,30,40,50)
print(tupla[1:4])   # (20, 30, 40)
print(tupla[:3])    # (10, 20, 30)
print(tupla[::2])   # (10, 30, 50)

# Iteración con tuplas
colores = ("rojo", "verde", "azul")
for color in colores:
    print(color)

# Tuplas anidadas
t = ((1,2),(3,4),(5,6))
print(t[0])     # (1,2)
print(t[0][1])  # 2

# Concatenación de tuplas
t1 =(1,2,3)
t2 =(4,5,6)
resultado = t1 + t2
print(resultado)   # (1,2,3,4,5,6)

# Repetición de elementos en tuplas
t1 = ("python",) *3
print(t1)   # ('python', 'python', 'python')

# Verificar pertenencia
t = (10,20,30,40)
print(20 in t)       # True
print(5 not in t)    # True

# Desempaquetar tuplas
persona = ("nicolas", 22, "colombia")
nombre, edad, pais= persona
print(nombre)
print(edad)
print(pais)

# Métodos count() e index()
t = (1,2,2,3,4,5)
print(t.count(2))  # Cuenta cuántas veces aparece el 2
print(t.index(3))  # Devuelve la posición de 3

# Funciones integradas con tuplas
t = (5,1,7,3)
print(len(t))       # Longitud de la tupla
print(max(t))       # Máximo
print(min(t))       # Mínimo
print(sum(t))       # Suma de elementos
print(sorted(t))    # Lista ordenada de la tupla

# Convertir lista en tupla
lista = [1,2,3]
tupla = tuple(lista)
print(tupla)

# Convertir tupla en lista
nueva_lista = list(tupla)
print(nueva_lista)

# Ejemplo práctico: acceso por índice
persona = ("Nicolas",22,"Colombia")
print("Nombre:",persona[0])
print("Edad:",persona[1])
print("Pais:",persona[2])

# Uso de tuplas como clave en diccionarios
cordenadas = {}
punto = (10,20)
cordenadas[punto] = "Ubicacion A"
print(cordenadas)

# Función que devuelve múltiples resultados usando tuplas
def operacion (a,b):
  return a + b, a - b, a * b

suma,resta,producto = operacion(5,3)
print(suma,resta,producto)

# Uso de enumerate con tuplas
frutas = ("manzana", "banana", "cereza")
for i, fruta in enumerate(frutas):
  print(i, fruta)

# Intercambio de valores con tuplas
a, b = 10,20
a, b = b, a
print(a,b)

"""
# ===============================
# EJERCICIOS
# ==============================="""

# Ejercicio 1 – Crear una tupla
t = (1, 2, 3, 4, 5)
print(t) # (1, 2, 3, 4, 5)

# Ejercicio 2 – Acceder al tercer elemento
t = (10, 20, 30, 40, 50)
print(t[2]) # 30

# Ejercicio 3 – Tupla con nombre y edad
info = ("Nicolás", 22)
print("Nombre:", info[0], "Edad:", info[1])

# Ejercicio 4 – Concatenar tuplas
t1 = (1, 2, 3)
t2 = (4, 5, 6)
print(t1 + t2) # (1, 2, 3, 4, 5, 6)

# Ejercicio 5 – Repetir una tupla
t = ("Python",) * 3
print(t) # ('Python', 'Python', 'Python')

# Ejercicio 6 – Verificar pertenencia
t = (5, 10, 15, 20, 25)
print(20 in t) # True

# Ejercicio 7 – Desempaquetar tupla
paises = ("Colombia", "México", "Argentina")
a, b, c = paises
print(a, b, c) # Colombia México Argentina

# Ejercicio 8 – Tupla anidada
t = ((1, 2), (3, 4))
print(t[1][1]) # 4

# Ejercicio 9 – Función con suma y producto
def operaciones(a, b):
    return a+b, a*b
print(operaciones(3, 5)) # (8, 15)

# Ejercicio 10 – Intercambio de valores
a, b = 7, 9
a, b = b, a
print(a, b) # 9 7

# Ejercicio 11 – Contar apariciones
t = (2, 4, 6, 2, 8, 2)
print(t.count(2)) # 3

# Ejercicio 12 – Índice de un valor
t = (10, 20, 30, 40, 50)
print(t.index(50)) # 4

# Ejercicio 13 – Funciones integradas
t = (4, 7, 1, 9, 3)
print(max(t)) # 9
print(min(t)) # 1
print(sum(t)) # 24

# Ejercicio 14 – Convertir lista a tupla
lista = [10, 20, 30]
t = tuple(lista)
print(t) # (10, 20, 30)

# Ejercicio 15 – Enumerate con tuplas
colores = ("rojo", "verde", "azul")
for i, color in enumerate(colores):
    print(i, color)