# -*- coding: utf-8 -*-
"""Calificacion_Parcial_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-m4InaFs7jk5hI97JJ2uoQcz-PwX4lj
"""

Carrito = []

while True:

  print("Menu del Carrito")
  print("Agregar al Carrito")
  print("Eliminar Productos")
  print("Ver Carrito")
  print("Salir")

  opc = input("Elige una opcion:")

  if opc == "1":
    producto = input("Ingresa el nombre del producto:")
    Carrito.append(producto)
    print(producto,"agregado al carrito")

  elif opc == "2":
    producto = input("Ingresa el producto que quiere eliminar:")
    if producto in Carrito:
      Carrito.remove(producto)
      print(producto,"eliminado del carrito")
    else:
      print("El producto no esta en el carrito")

  elif opc == "3":
    if Carrito:
      print("Contenido del Carrito",Carrito)

    else:
      print("El carrito esta vacio")

  elif opc == "4":
    print("Saliendo del Progama")
    break
  else:
    print("Opcion invalida , intente de nuevo")

roles_validos = ("admin","editor","visitante")
usuarios = []
while True:
  print("Registrate")
  nombre = input("ingresqa nombre del usuario (o salir para terminar el para terminar):")
  if nombre.lower()== "salir":
    break
  rol = input("ingresar el rol(admin, editor, visitante):")

  if rol in roles_validos:
    usuarios.append((nombre,rol))
    print("usuario",nombre,"con rol",rol,"registrado")
  else:
    print("rol invalido,intentar de nuevo")

print("lista de usuarios registrados:")
for usuario in usuarios:
  print(usuarios)

Agenda = {}

while True:
  print("Menu de Agenda")
  print("1. Agregar Contacto")
  print("2. Buscar Contacto")
  print("3. Mostrar todos los contactos")
  print("4. Salir")
  opc = input("Elige una opcion:")

  if opc == "1":
    nombre = input("Ingresa el nombre del contacto:")
    telefono = input("Ingresa el telefono del contacto:")
    Agenda.update({nombre : telefono})
    print("contacto",nombre,"agendado")

  elif opc == "2":
    nombre = input("Nombre a buscar:")
    telefono = Agenda.get(nombre)
    if telefono:
      print(nombre,telefono)
    else:
      print("contacto inexistente")

  elif opc == "3":
    if Agenda:
      print("Lista de contactos:")
      for nombre,telefono in Agenda.items():
        print(nombre,telefono)
    else:
      print("Agenda vacia")

  elif opc == "4":
    print("Saliendo del programa")
    break

  else:
    print("Opcion invalida, intente de nuevo")

votos = {"rojo": 0 ,"Azul": 0 ,"Verde": 0 ,"Amarillo": 0}

while True:
  print("Votacion de colores Favoritos")
  print("colores disponibles:", list(votos.keys()))
  print("Escribe salir para terminar resultados")

  color = input("vota por un color:").lower()

  if color == "salir":
    break

  elif color in votos:
    votos[color] += 1
    print("voto registrado por",color)
  else:
    print("opcion invalida, intente de nuevo")

print("resultados de la votacion:")
for color,cantidad in votos.items():
  print(color,votos,"votos")