# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jXtk_rt0KhC6PlSjOk8bQYKEozMCx1Y

# ==============================
# PROGRAMA 1: CARRITO DE COMPRAS
# ==============================
"""

Carrito = []  # Lista vacía para almacenar productos

while True:   # Bucle infinito hasta que el usuario salga
  print("Menu del Carrito")
  print("Agregar al Carrito")
  print("Eliminar Productos")
  print("Ver Carrito")
  print("Salir")

  opc = input("Elige una opcion:")  # Se pide opción al usuario

  if opc == "1":   # Opción 1: Agregar producto
    producto = input("Ingresa el nombre del producto:")
    Carrito.append(producto)  # Agregar a la lista
    print(producto,"agregado al carrito")

  elif opc == "2":  # Opción 2: Eliminar producto
    producto = input("Ingresa el producto que quiere eliminar:")
    if producto in Carrito:       # Verifica si existe
      Carrito.remove(producto)    # Lo elimina
      print(producto,"eliminado del carrito")
    else:
      print("El producto no esta en el carrito")

  elif opc == "3":  # Opción 3: Ver el carrito
    if Carrito:  # Si no está vacío
      print("Contenido del Carrito",Carrito)
    else:
      print("El carrito esta vacio")

  elif opc == "4":  # Opción 4: Salir del programa
    print("Saliendo del Progama")
    break

  else:  # Si la opción no es válida
    print("Opcion invalida , intente de nuevo")

"""# ==============================
# PROGRAMA 2: REGISTRO DE USUARIOS
# ==============================

"""

}roles_validos = ("admin","editor","visitante")  # Roles permitidos
usuarios = []  # Lista para almacenar usuarios y roles

while True:
  print("Registrate")
  nombre = input("ingresqa nombre del usuario (o salir para terminar el para terminar):")
  if nombre.lower()== "salir":  # Si escribe salir, se rompe el ciclo
    break
  rol = input("ingresar el rol(admin, editor, visitante):")

  if rol in roles_validos:   # Si el rol es válido
    usuarios.append((nombre,rol))  # Se guarda como tupla
    print("usuario",nombre,"con rol",rol,"registrado")
  else:
    print("rol invalido,intentar de nuevo")

print("lista de usuarios registrados:")
for usuario in usuarios:
  print(usuarios)  # ⚠️ Aquí imprime la lista completa varias veces

"""# ==============================
# PROGRAMA 3: AGENDA DE CONTACTOS
# ==============================
"""

Agenda = {}  # Diccionario vacío para almacenar contactos

while True:
  print("Menu de Agenda")
  print("1. Agregar Contacto")
  print("2. Buscar Contacto")
  print("3. Mostrar todos los contactos")
  print("4. Salir")
  opc = input("Elige una opcion:")

  if opc == "1":   # Agregar contacto
    nombre = input("Ingresa el nombre del contacto:")
    telefono = input("Ingresa el telefono del contacto:")
    Agenda.update({nombre : telefono})  # Agregar al diccionario
    print("contacto",nombre,"agendado")

  elif opc == "2":  # Buscar contacto
    nombre = input("Nombre a buscar:")
    telefono = Agenda.get(nombre)  # Busca en el diccionario
    if telefono:
      print(nombre,telefono)
    else:
      print("contacto inexistente")

  elif opc == "3":  # Mostrar todos
    if Agenda:
      print("Lista de contactos:")
      for nombre,telefono in Agenda.items():
        print(nombre,telefono)
    else:
      print("Agenda vacia")

  elif opc == "4":  # Salir
    print("Saliendo del programa")
    break

  else:
    print("Opcion invalida, intente de nuevo")

"""# ==============================
# PROGRAMA 4: VOTACIÓN DE COLORES
# ==============================
"""

# Diccionario para contar votos por color
votos = {"rojo": 0 ,"azul": 0 ,"verde": 0 ,"amarillo": 0}

while True:
  print("Votacion de colores Favoritos")
  print("colores disponibles:", list(votos.keys()))
  print("Escribe salir para terminar resultados")

  color = input("vota por un color:").lower()  # Se pasa a minúscula

  if color == "salir":
    break

  elif color in votos:   # ⚠️ Aquí hay un problema: las claves no están todas en minúsculas
    votos[color] += 1
    print("voto registrado por",color)
  else:
    print("opcion invalida, intente de nuevo")

print("resultados de la votacion:")
for color,cantidad in votos.items():
  print(color,votos,"votos")  # ⚠️ Aquí imprime todo el diccionario en lugar de la cantidad